theme = "slick"
icons = "awesome"

[[block]]
block = "focused_window"
# max_width = 25

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB ({Mup}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

# [[block]]
# block = "net"
# device = "wlp4s0"
# ssid = true
# ip = true
# speed_up = false
# graph_up = true
# interval = 5

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} km/s"
service = { name = "openweathermap", api_key = "d2babfddec55c71419de401e98172c02", city_id = "2972315", units = "metric" }

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"
show_volume_when_muted = true

[[block]]
block = "bluetooth"
mac = "04:52:C7:5E:BF:77"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "xrandr"
icons = true
resolution = true
interval = 2

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M"

[[block]]
block = "battery"
